//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SampWzd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SAMPLEWZD_DIALOG            102
#define IDD_PAGE1                       102
#define IDR_MAINFRAME                   128
#define IDD_PAGE2                       129
#define IDD_PAGE3                       130
#define IDD_PAGE4                       131
#define IDD_PAGE5                       132
#define IDB_BITMAP1                     135
#define IDB_BITMAP2                     137
#define IDB_BITMAP3                     138
#define IDB_BITMAP4                     139
#define IDD_DIALOG1                     140
#define IDC_PAGE3_CHECK                 1000
#define IDC_LIST1                       1001
#define IDC_SPIN1                       1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_EDIT3                       1005
#define IDC_CHECK1                      1007
#define IDC_CHECK2                      1008
#define IDC_BUTTON1                     1010
#define IDC_BUTTON2                     1011
#define IDC_COMBO1                      1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
