// Server.idl : IDL source for Server.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Server.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(4832AAD4-AB3F-11D3-8081-000000000000),
		dual,
		helpstring("IWzd Interface"),
		pointer_default(unique)
	]
	interface IWzd : IDispatch
	{
		[id(1), helpstring("method Method1")] HRESULT Method1([in] long lArg);
	};
	[
		object,
		uuid(4832AAD5-AB3F-11D3-8081-000000000000),
		dual,
		helpstring("IWzdEx Interface"),
		pointer_default(unique)
	]
	interface IWzdEx : IDispatch
	{
		[id(1), helpstring("method Method2")] HRESULT Method2([in]long lArg);
	};

[
	uuid(4832AAC8-AB3F-11D3-8081-000000000000),
	version(1.0),
	helpstring("Server 1.0 Type Library")
]
library SERVERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(351495D1-AA6D-11D3-807E-000000000000),
		helpstring("Wzd Class")
	]
	coclass Wzd
	{
		[default] interface IWzd;
	};
	[
		uuid(4832AAD6-AB3F-11D3-8081-000000000000),
		helpstring("WzdEx Class")
	]
	coclass WzdEx
	{
		[default] interface IWzdEx;
	};
};
