// AggSvr.idl : IDL source for AggSvr.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (AggSvr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(853B853E-A88A-11D3-A398-00C04F570E2C),
		dual,
		helpstring("IWzdAgSvr Interface"),
		pointer_default(unique)
	]
	interface IWzdAgSvr : IDispatch
	{
		[id(1), helpstring("method Method1")] HRESULT Method1([in] long lArg, [out] long *plArg);
	};

[
	uuid(853B8532-A88A-11D3-A398-00C04F570E2C),
	version(1.0),
	helpstring("AggSvr 1.0 Type Library")
]
library AGGSVRLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(853B853F-A88A-11D3-A398-00C04F570E2C),
		helpstring("WzdAgSvr Class")
	]
	coclass WzdAgSvr
	{
		[default] interface IWzdAgSvr;
	};
};
