// Machine generated IDispatch wrapper class(es) created with ClassWizard
/////////////////////////////////////////////////////////////////////////////
// IWzd wrapper class

class IWzd : public COleDispatchDriver
{
public:
	IWzd() {}		// Calls COleDispatchDriver default constructor
	IWzd(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	IWzd(const IWzd& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetProperty1();
	void SetProperty1(long);

// Operations
public:
	void Method1(long lArg);
};
